version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/docker/image
    overwrite: yes

permissions:
  - object: /home/ubuntu/docker
    owner: root
    group: root
    mode: 755

hooks:
  hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root




